name: CI - Build Test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: deps backend
        run: |
          cd backend
          bun install

      - name: set backend env
        run: |
          echo "APP_KEYS=key1,key2" > backend/.env
          echo "API_TOKEN_SALT=toBeModified" >> backend/.env
          echo "ADMIN_JWT_SECRET=toBeModified" >> backend/.env
          echo "TRANSFER_TOKEN_SALT=toBeModified" >> backend/.env
          echo "JWT_SECRET=toBeModified" >> backend/.env
          echo "NEXT_PUBLIC_URL=http://127.0.0.1:3000" >> backend/.env
          echo "REVALIDATION_SECRET=toBeModified" >> backend/.env

      - name: set frontend env
        run: |
          echo "REVALIDATION_SECRET=toBeModified" > frontend/.env

      - name: deps frontend
        run: |
          cd frontend
          bun install

      - name: deps root
        run: |
          bun install

      - name: import strapi data
        run: |
          cd backend
          bun ci:import-strapi-data

      - name: build backend
        run: |
          cd backend
          bun run build

      - name: run backend and build frontend
        run: |
          bun run ci
