name: CI - Build Test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the backend
      - name: deps backend
        run: |
          cd backend
          npm install

      # Step 3: Build the frontend
      - name: deps frontend
        run: |
          cd frontend
          npm install

      - name: build frontend and backend
        run: |
          npm run ci
